version: "2"
services:
  server:
    build: ./modbus-server
    restart: unless-stopped
  client:
    build: ./modbus-client
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

